### ISSUE TITLE
DanceTeam can Dance again

### ISSUE THREAD

**Issue by sparzentny** [drbv/judge_tool#12]
Because of a disturbance in the Force a danceteam can dance again.
If this happens the admin should be able to enable this. The Couple will be placed in an additional Dance Round at the end of the Round. The Round can not be closed until they have danced

**Comment by snookyly** [comment]
this functionality will better fit in the workflow of the observer. When the disturbance occur, the observer has the dance team on his current view anyways. There can be a button "dance again at the end" in that very view, where he can insert his mistakes. The admin will not be in front of the machine when  the disturbance occur, but the observer.
Therefore the admin will request the observer to push the button.

**Comment by sparzentny** [comment]
Because the admin is getting more and more methods. He can do this in his own view

**Comment by sparzentny** [comment]
The Admin can mark DanceTeams to dance again. They will be attached to the next possible dance_round. this could be a new dance_round or an existing  wit only 1 DacneTeam. The ratings from the repeated Team will override the ratings from the original dance_round.

**Comment by sparzentny** [comment]
added but not fully tested
