### ISSUE TITLE
"Turnierleiter muss den Beginn einer Tanzklasse freigeben" könnte wegfallen

### ISSUE THREAD

**Issue by snookyly** [drbv/judge_tool#18]
Der Knopf, mit dem der Turnierleiter eine Tanzklasse startet, kann wegfallen. Die erste Tanzklasse muss der TL freigeben. Wenn zu dem Zeitpunkt noch keine Rundenauslosung, dann Fehler. Wenn Rundenauslosung vorhanden ist, dann starten. 

Und dann vor Beginn der nächsten Tanzklasse prüfen, ob die Rundenauslosung vorhanden ist. Wenn nicht Fehler, wenn vorhanden, dann ohne Eingriff der TL Tanzklasse freigeben.

Dazu ist notwendig, dass "Nicht-Tanzklassen" nicht gestartet werden brauchen.

**Comment by sparzentny** [comment]
Damit das Programm nicht den Turnierleiter abhängt, möchte ich gerne an diesem Prozess festhalten. abgesehen von den Nicht-Tanzklassen.
