### ISSUE TITLE
roter Button Löschen in der Rundenverwaltung beim admin

### ISSUE THREAD

**Issue by snookyly** [drbv/judge_tool#22]
Wozu ist der Löschen Button? Der steht hinter "Ende der Veranstaltung". Wenn der Admin damit Elemente aus dem Zeitplan löschen kann, ist es zu überlegen ob er dort richtig platziert ist.

**Comment by sparzentny** [comment]
Der Button dient dazu, runden aus dem Judge Tool zu löschen, damit sie neu aus der MDB importiert werden können.
z.B. Bei streichen einer Runde. oder ähnlichem
