### ISSUE TITLE
In der Observerübersicht "Keine Fehler" durch Leerstring ersetzen

### ISSUE THREAD

**Issue by snookyly** [drbv/judge_tool#24]
In der Observerübersicht gilt die will der Observer schnell relevante Informationen ablesen. Der Text "Keine Fehler" wenn ein WR kein GF gewertet hat, ist eher hinderlich. Besser ist die Stelle leer zu lassen. Das hat den Vorteil, dass man sofort erkennt, wenn dort ein GF steht.

**Comment by sparzentny** [comment]
String wurde auf "-" geändert
