### ISSUE TITLE
Datenbank lässt sich nach Vorrunden nicht erneut importieren

### ISSUE THREAD

**Issue by snookyly** [drbv/judge_tool#27]
Wenn nach etwa zwei Vorrunden die MDB erneut importiert werden soll, schlägt der Improt fehlt. Löscht man den tmp Ordner, funktioniert der Import. Kann vor dem Import der tmp Ordner automatisch geleert werden?

**Comment by sparzentny** [comment]
haben wir gestern getestet, funktioniert. Es kann immer nur das gleiche Turnier hochgeladen werden. Wir prüfen dies über den Filenamen
