### ISSUE TITLE
zusätzliche Bestätigung beim absenden 

### ISSUE THREAD

**Issue by lambda4-ab** [drbv/judge_tool#30]
Bei jeder Abgabe der Wertungen bzw. Korrekturen durch den Observer wird die eingebende Person gefragt ob man wirklich alles eingegeben hat.

**Comment by sparzentny** [comment]
Evtl wäre ein zweimal zu drückender Button geeignet, der beim ersten mal quasi alles lockt und beim zweiten mal absendet.
