### ISSUE TITLE
shoutbox needed

### ISSUE THREAD

**Issue by bpieck** [drbv/judge_tool#8]
We should add a shoutbox - for some open discussions between judges - but also for private system messages. In this way we can publish the mistake majority adjustment there and ensure the judge will get this message, whichever flow it follows after majority adjustment.

**Comment by snookyly** [comment]
Hierbei ist zu beachten, dass die Zeit zwischen Wertung absenden und neues Tanzpaar steht auf der Fläche und fängt zu tanzen an, relativ kurz ist. Im Idealfall weniger als 20 oder 30 Sekunden. Es ist also keine Zeit da großartig zu chatten. Auch Statusmeldungen über den Mehrheitsbeschluss sind eventuell störend.
